### PR TITLE
CONTRIBUTING.md: code fences, repair Markdown

### PR DESCRIPTION
**Pull request by olleolleolle**
This PR fixes rendering of the Markdown in the CONTRIBUTING docs.

Issue fixed: A missing code fence after some commands

### CODE REVIEW

**Comment by dblock** [comment]
Looks like Travis is not building these PRs for some reason - care to fix the build too?

**Comment by olleolleolle** [comment]
@dblock I am purposefully adding a marker `[ci skip]` to avoid useless building.

**Comment by olleolleolle** [comment]
Oh, sorry, I mis-read you - sure, I can take a crack at it.

**Comment by dblock** [comment]
Ah yes I see why Travis is doing it now, but would love some help with the build and this gem in general (like the next release, etc.). LMK if you're interested.

**Pull request merged**
