### PR TITLE
Travis: use pre-installed Ruby

### PR DESCRIPTION
**Pull request by olleolleolle**
This PR tries to fix the build:

- use Travis' pre-installed Ruby versions
- update linting tools, and follow the linting rules
- add the license of `diff-lcs` to the config.yml, so as to pass a test

### CODE REVIEW

**Comment by olleolleolle** [comment]
```
NoMethodError: undefined method `last_comment' for #<Rake::Application:0x00000000c41530>
/home/travis/build/dblock/gem-licenses/vendor/bundle/ruby/2.2.0/gems/rubocop-0.29.1/lib/rubocop/rake_task.rb:23:in `initialize'
/home/travis/build/dblock/gem-licenses/Rakefile:12:in `new'
/home/travis/build/dblock/gem-licenses/Rakefile:12:in `<top (required)>'
/home/travis/build/dblock/gem-licenses/vendor/bundle/ruby/2.2.0/gems/rake-12.2.1/exe/rake:27:in `<top (required)>'
/home/travis/.rvm/gems/ruby-2.2.7/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:74:in `load'
/home/travis/.rvm/gems/ruby-2.2.7/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:74:in `kernel_load'
/home/travis/.rvm/gems/ruby-2.2.7/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:27:in `run'
/home/travis/.rvm/gems/ruby-2.2.7/gems/bundler-1.15.4/lib/bundler/cli.rb:362:in `exec'
/home/travis/.rvm/gems/ruby-2.2.7/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/travis/.rvm/gems/ruby-2.2.7/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/travis/.rvm/gems/ruby-2.2.7/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/home/travis/.rvm/gems/ruby-2.2.7/gems/bundler-1.15.4/lib/bundler/cli.rb:22:in `dispatch'
/home/travis/.rvm/gems/ruby-2.2.7/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/home/travis/.rvm/gems/ruby-2.2.7/gems/bundler-1.15.4/lib/bundler/cli.rb:13:in `start'
/home/travis/.rvm/gems/ruby-2.2.7/gems/bundler-1.15.4/exe/bundle:30:in `block in <top (required)>'
/home/travis/.rvm/gems/ruby-2.2.7/gems/bundler-1.15.4/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/home/travis/.rvm/gems/ruby-2.2.7/gems/bundler-1.15.4/exe/bundle:22:in `<top (required)>'
/home/travis/.rvm/gems/ruby-2.2.7/bin/bundle:22:in `load'
/home/travis/.rvm/gems/ruby-2.2.7/bin/bundle:22:in `<main>'
/home/travis/.rvm/gems/ruby-2.2.7/bin/ruby_executable_hooks:15:in `eval'
/home/travis/.rvm/gems/ruby-2.2.7/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by dblock** [comment]
I think it needs an upgrade of Rake, Rubocop, etc.

**Comment by olleolleolle** [comment]
@dblock There we go - linted upgraded and let's see!

**Comment by olleolleolle** [comment]
@dblock Somehow, the output of the licenses' keys seems to be

```
["MIT", "artistic-2.0", "gpl-2.0+"]

```

**Comment by olleolleolle** [comment]
@dblock Should I add a config.yml row like

`gpl-2.0+: GPLv2`

**Comment by olleolleolle** [comment]
[diff-lcs](https://rubygems.org/gems/diff-lcs/) has that weird license.

**Comment by olleolleolle** [comment]
@dblock There!

**Pull request merged**
